#
# Makefile
#

ccflags-y += -I${HOME}/gcc-arm-none-eabi-4_9-2015q1/arm-none-eabi/include
ccflags-y += -L${HOME}/gcc-arm-none-eabi-4_9-2015q1/arm-none-eabi/lib/libc.a -L${HOME}/gcc-arm-none-eabi-4_9-2015q1/arm-none-eabi/lib/libm.a
# ccflags-y += -lc -lm

$(warning '$(ccflags-y)')

obj-y := main.o

