#
# Makefile
#

ccflags-y += -I${HOME}/work/gcc-arm-none-eabi-5_4-2016q3/arm-none-eabi/include
# ccflags-y += -L${HOME}/work/gcc-arm-none-eabi-5_4-2016q3/arm-none-eabi/lib/libc.a -L${HOME}/gcc-arm-none-eabi-4_9-2015q1/arm-none-eabi/lib/libm.a
ccflags-y += -lc
# ccflags-y += -lc -lm

$(warning '$(ccflags-y)')

obj-y := main.o

